name: Update Bootswatch

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  update-bootswatch:
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/update') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,test]"
      - name: Install
        run: |
          make install

      - name: Run `scripts/update_bootswatch.py`
        run: |
          python3 scripts/update_bootswatch.py

      - name: Push back changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add shinyswatch/_themes.py || echo "No Bootswatch changes to add"
          git commit -m 'Update Bootswatch themes (GitHub Actions)' || echo "No Bootswatch changes to commit"
          git push
